const CC =
    [
        { id: 'af', label: 'AFGHANISTAN' },
        { id: 'ax', label: 'ÅLAND ISLANDS' },
        { id: 'al', label: 'ALBANIA' },
        { id: 'dz', label: 'ALGERIA' },
        { id: 'as', label: 'AMERICAN SAMOA' },
        { id: 'ad', label: 'ANDORRA' },
        { id: 'ao', label: 'ANGOLA' },
        { id: 'ai', label: 'ANGUILLA' },
        { id: 'aq', label: 'ANTARCTICA' },
        { id: 'ag', label: 'ANTIGUA AND BARBUDA' },
        { id: 'ar', label: 'ARGENTINA' },
        { id: 'am', label: 'ARMENIA' },
        { id: 'aw', label: 'ARUBA' },
        { id: 'au', label: 'AUSTRALIA' },
        { id: 'at', label: 'AUSTRIA' },
        { id: 'az', label: 'AZERBAIJAN' },
        { id: 'bs', label: 'BAHAMAS' },
        { id: 'bh', label: 'BAHRAIN' },
        { id: 'bd', label: 'BANGLADESH' },
        { id: 'bb', label: 'BARBADOS' },
        { id: 'by', label: 'BELARUS' },
        { id: 'be', label: 'BELGIUM' },
        { id: 'bz', label: 'BELIZE' },
        { id: 'bj', label: 'BENIN' },
        { id: 'bm', label: 'BERMUDA' },
        { id: 'bt', label: 'BHUTAN' },
        { id: 'bo', label: 'BOLIVIA, PLURINATIONAL STATE OF' },
        { id: 'bq', label: 'BONAIRE, SINT EUSTATIUS AND SABA' },
        { id: 'ba', label: 'BOSNIA AND HERZEGOVINA' },
        { id: 'bw', label: 'BOTSWANA' },
        { id: 'bv', label: 'BOUVET ISLAND' },
        { id: 'br', label: 'BRAZIL' },
        { id: 'io', label: 'BRITISH INDIAN OCEAN TERRITORY' },
        { id: 'bn', label: 'BRUNEI DARUSSALAM' },
        { id: 'bg', label: 'BULGARIA' },
        { id: 'bf', label: 'BURKINA FASO' },
        { id: 'bi', label: 'BURUNDI' },
        { id: 'kh', label: 'CAMBODIA' },
        { id: 'cm', label: 'CAMEROON' },
        { id: 'ca', label: 'CANADA' },
        { id: 'cv', label: 'CAPE VERDE' },
        { id: 'ky', label: 'CAYMAN ISLANDS' },
        { id: 'cf', label: 'CENTRAL AFRICAN REPUBLIC' },
        { id: 'td', label: 'CHAD' },
        { id: 'cl', label: 'CHILE' },
        { id: 'cn', label: 'CHINA' },
        { id: 'cx', label: 'CHRISTMAS ISLAND' },
        { id: 'cc', label: 'COCOS (KEELING) ISLANDS' },
        { id: 'co', label: 'COLOMBIA' },
        { id: 'km', label: 'COMOROS' },
        { id: 'cg', label: 'CONGO' },
        { id: 'cd', label: 'CONGO, THE DEMOCRATIC REPUBLIC OF THE' },
        { id: 'ck', label: 'COOK ISLANDS' },
        { id: 'cr', label: 'COSTA RICA' },
        { id: 'ci', label: 'CÔTE D\'IVOIRE' },
        { id: 'hr', label: 'CROATIA' },
        { id: 'cu', label: 'CUBA' },
        { id: 'cw', label: 'CURAÇAO' },
        { id: 'cy', label: 'CYPRUS' },
        { id: 'cz', label: 'CZECH REPUBLIC' },
        { id: 'dk', label: 'DENMARK' },
        { id: 'dj', label: 'DJIBOUTI' },
        { id: 'dm', label: 'DOMINICA' },
        { id: 'do', label: 'DOMINICAN REPUBLIC' },
        { id: 'ec', label: 'ECUADOR' },
        { id: 'eg', label: 'EGYPT' },
        { id: 'sv', label: 'EL SALVADOR' },
        { id: 'gq', label: 'EQUATORIAL GUINEA' },
        { id: 'er', label: 'ERITREA' },
        { id: 'ee', label: 'ESTONIA' },
        { id: 'et', label: 'ETHIOPIA' },
        { id: 'fk', label: 'FALKLAND ISLANDS (MALVINAS)' },
        { id: 'fo', label: 'FAROE ISLANDS' },
        { id: 'fj', label: 'FIJI' },
        { id: 'fi', label: 'FINLAND' },
        { id: 'fr', label: 'FRANCE' },
        { id: 'gf', label: 'FRENCH GUIANA' },
        { id: 'pf', label: 'FRENCH POLYNESIA' },
        { id: 'tf', label: 'FRENCH SOUTHERN TERRITORIES' },
        { id: 'ga', label: 'GABON' },
        { id: 'gm', label: 'GAMBIA' },
        { id: 'ge', label: 'GEORGIA' },
        { id: 'de', label: 'GERMANY' },
        { id: 'gh', label: 'GHANA' },
        { id: 'gi', label: 'GIBRALTAR' },
        { id: 'gr', label: 'GREECE' },
        { id: 'gl', label: 'GREENLAND' },
        { id: 'gd', label: 'GRENADA' },
        { id: 'gp', label: 'GUADELOUPE' },
        { id: 'gu', label: 'GUAM' },
        { id: 'gt', label: 'GUATEMALA' },
        { id: 'gg', label: 'GUERNSEY' },
        { id: 'gn', label: 'GUINEA' },
        { id: 'gw', label: 'GUINEA-BISSAU' },
        { id: 'gy', label: 'GUYANA' },
        { id: 'ht', label: 'HAITI' },
        { id: 'hm', label: 'HEARD ISLAND AND MCDONALD ISLANDS' },
        { id: 'va', label: 'HOLY SEE (VATICAN CITY STATE)' },
        { id: 'hn', label: 'HONDURAS' },
        { id: 'hk', label: 'HONG KONG' },
        { id: 'hu', label: 'HUNGARY' },
        { id: 'is', label: 'ICELAND' },
        { id: 'in', label: 'INDIA' },
        { id: 'id', label: 'INDONESIA' },
        { id: 'ir', label: 'IRAN, ISLAMIC REPUBLIC OF' },
        { id: 'iq', label: 'IRAQ' },
        { id: 'ie', label: 'IRELAND' },
        { id: 'im', label: 'ISLE OF MAN' },
        { id: 'il', label: 'ISRAEL' },
        { id: 'it', label: 'ITALY' },
        { id: 'jm', label: 'JAMAICA' },
        { id: 'jp', label: 'JAPAN' },
        { id: 'je', label: 'JERSEY' },
        { id: 'jo', label: 'JORDAN' },
        { id: 'kz', label: 'KAZAKHSTAN' },
        { id: 'ke', label: 'KENYA' },
        { id: 'ki', label: 'KIRIBATI' },
        { id: 'kp', label: 'KOREA, DEMOCRATIC PEOPLE\'S REPUBLIC OF' },
        { id: 'kr', label: 'KOREA, REPUBLIC OF' },
        { id: 'kw', label: 'KUWAIT' },
        { id: 'kg', label: 'KYRGYZSTAN' },
        { id: 'la', label: 'LAO PEOPLE\'S DEMOCRATIC REPUBLIC' },
        { id: 'lv', label: 'LATVIA' },
        { id: 'lb', label: 'LEBANON' },
        { id: 'ls', label: 'LESOTHO' },
        { id: 'lr', label: 'LIBERIA' },
        { id: 'ly', label: 'LIBYA' },
        { id: 'li', label: 'LIECHTENSTEIN' },
        { id: 'lt', label: 'LITHUANIA' },
        { id: 'lu', label: 'LUXEMBOURG' },
        { id: 'mo', label: 'MACAO' },
        { id: 'mk', label: 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF' },
        { id: 'mg', label: 'MADAGASCAR' },
        { id: 'mw', label: 'MALAWI' },
        { id: 'my', label: 'MALAYSIA' },
        { id: 'mv', label: 'MALDIVES' },
        { id: 'ml', label: 'MALI' },
        { id: 'mt', label: 'MALTA' },
        { id: 'mh', label: 'MARSHALL ISLANDS' },
        { id: 'mq', label: 'MARTINIQUE' },
        { id: 'mr', label: 'MAURITANIA' },
        { id: 'mu', label: 'MAURITIUS' },
        { id: 'yt', label: 'MAYOTTE' },
        { id: 'mx', label: 'MEXICO' },
        { id: 'fm', label: 'MICRONESIA, FEDERATED STATES OF' },
        { id: 'md', label: 'MOLDOVA, REPUBLIC OF' },
        { id: 'mc', label: 'MONACO' },
        { id: 'mn', label: 'MONGOLIA' },
        { id: 'me', label: 'MONTENEGRO' },
        { id: 'ms', label: 'MONTSERRAT' },
        { id: 'ma', label: 'MOROCCO' },
        { id: 'mz', label: 'MOZAMBIQUE' },
        { id: 'mm', label: 'MYANMAR' },
        { id: 'na', label: 'NAMIBIA' },
        { id: 'nr', label: 'NAURU' },
        { id: 'np', label: 'NEPAL' },
        { id: 'nl', label: 'NETHERLANDS' },
        { id: 'nc', label: 'NEW CALEDONIA' },
        { id: 'nz', label: 'NEW ZEALAND' },
        { id: 'ni', label: 'NICARAGUA' },
        { id: 'ne', label: 'NIGER' },
        { id: 'ng', label: 'NIGERIA' },
        { id: 'nu', label: 'NIUE' },
        { id: 'nf', label: 'NORFOLK ISLAND' },
        { id: 'mp', label: 'NORTHERN MARIANA ISLANDS' },
        { id: 'no', label: 'NORWAY' },
        { id: 'om', label: 'OMAN' },
        { id: 'pk', label: 'PAKISTAN' },
        { id: 'pw', label: 'PALAU' },
        { id: 'ps', label: 'PALESTINE, STATE OF' },
        { id: 'pa', label: 'PANAMA' },
        { id: 'pg', label: 'PAPUA NEW GUINEA' },
        { id: 'py', label: 'PARAGUAY' },
        { id: 'pe', label: 'PERU' },
        { id: 'ph', label: 'PHILIPPINES' },
        { id: 'pn', label: 'PITCAIRN' },
        { id: 'pl', label: 'POLAND' },
        { id: 'pt', label: 'PORTUGAL' },
        { id: 'pr', label: 'PUERTO RICO' },
        { id: 'qa', label: 'QATAR' },
        { id: 're', label: 'RÉUNION' },
        { id: 'ro', label: 'ROMANIA' },
        { id: 'ru', label: 'RUSSIAN FEDERATION' },
        { id: 'rw', label: 'RWANDA' },
        { id: 'bl', label: 'SAINT BARTHÉLEMY' },
        { id: 'sh', label: 'SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA' },
        { id: 'kn', label: 'SAINT KITTS AND NEVIS' },
        { id: 'lc', label: 'SAINT LUCIA' },
        { id: 'mf', label: 'SAINT MARTIN (FRENCH PART)' },
        { id: 'pm', label: 'SAINT PIERRE AND MIQUELON' },
        { id: 'vc', label: 'SAINT VINCENT AND THE GRENADINES' },
        { id: 'ws', label: 'SAMOA' },
        { id: 'sm', label: 'SAN MARINO' },
        { id: 'st', label: 'SAO TOME AND PRINCIPE' },
        { id: 'sa', label: 'SAUDI ARABIA' },
        { id: 'sn', label: 'SENEGAL' },
        { id: 'rs', label: 'SERBIA' },
        { id: 'sc', label: 'SEYCHELLES' },
        { id: 'sl', label: 'SIERRA LEONE' },
        { id: 'sg', label: 'SINGAPORE' },
        { id: 'sx', label: 'SINT MAARTEN (DUTCH PART)' },
        { id: 'sk', label: 'SLOVAKIA' },
        { id: 'si', label: 'SLOVENIA' },
        { id: 'sb', label: 'SOLOMON ISLANDS' },
        { id: 'so', label: 'SOMALIA' },
        { id: 'za', label: 'SOUTH AFRICA' },
        { id: 'gs', label: 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS' },
        { id: 'ss', label: 'SOUTH SUDAN' },
        { id: 'es', label: 'SPAIN' },
        { id: 'lk', label: 'SRI LANKA' },
        { id: 'sd', label: 'SUDAN' },
        { id: 'sr', label: 'SURINAME' },
        { id: 'sj', label: 'SVALBARD AND JAN MAYEN' },
        { id: 'sz', label: 'SWAZILAND' },
        { id: 'se', label: 'SWEDEN' },
        { id: 'ch', label: 'SWITZERLAND' },
        { id: 'sy', label: 'SYRIAN ARAB REPUBLIC' },
        { id: 'tw', label: 'TAIWAN, PROVINCE OF CHINA' },
        { id: 'tj', label: 'TAJIKISTAN' },
        { id: 'tz', label: 'TANZANIA, UNITED REPUBLIC OF' },
        { id: 'th', label: 'THAILAND' },
        { id: 'tl', label: 'TIMOR-LESTE' },
        { id: 'tg', label: 'TOGO' },
        { id: 'tk', label: 'TOKELAU' },
        { id: 'to', label: 'TONGA' },
        { id: 'tt', label: 'TRINIDAD AND TOBAGO' },
        { id: 'tn', label: 'TUNISIA' },
        { id: 'tr', label: 'TURKEY' },
        { id: 'tm', label: 'TURKMENISTAN' },
        { id: 'tc', label: 'TURKS AND CAICOS ISLANDS' },
        { id: 'tv', label: 'TUVALU' },
        { id: 'ug', label: 'UGANDA' },
        { id: 'ua', label: 'UKRAINE' },
        { id: 'ae', label: 'UNITED ARAB EMIRATES' },
        { id: 'gb', label: 'UNITED KINGDOM' },
        { id: 'us', label: 'UNITED STATES' },
        { id: 'um', label: 'UNITED STATES MINOR OUTLYING ISLANDS' },
        { id: 'uy', label: 'URUGUAY' },
        { id: 'uz', label: 'UZBEKISTAN' },
        { id: 'vu', label: 'VANUATU' },
        { id: 've', label: 'VENEZUELA, BOLIVARIAN REPUBLIC OF' },
        { id: 'vn', label: 'VIET NAM' },
        { id: 'vg', label: 'VIRGIN ISLANDS, BRITISH' },
        { id: 'vi', label: 'VIRGIN ISLANDS, U.S.' },
        { id: 'wf', label: 'WALLIS AND FUTUNA' },
        { id: 'eh', label: 'WESTERN SAHARA' },
        { id: 'ye', label: 'YEMEN' },
        { id: 'zm', label: 'ZAMBIA' },
        { id: 'zw', label: 'ZIMBABWE' }
    ]


export { CC }